### ISSUE TITLE
subject id's different in wBrainVols

### ISSUE THREAD

**Issue by satra** [dbkeator/simple2_NIDM_examples#1]
@dbkeator - the subject IDs associated with the clinical info is different from the info associated with the freesurfer info. i think this comes from the two different pieces you are processing.

so ideally there should be one prov agent for subject id.

```
niiri:d1404e48-b25f-11e9-84fd-003ee1ce9545 a onli:instrument-based-assessment,
        nidm:Acquisition,
        prov:Activity ;
    prov:wasAssociatedWith niiri:d14054a6-b25f-11e9-84fd-003ee1ce9545 .

niiri:d14054a6-b25f-11e9-84fd-003ee1ce9545 a prov:Agent,
        prov:Person ;
    ndar:src_subject_id "26005"^^xsd:string .
```
and

```
niiri:225c29f6-b3db-11e9-9296-003ee1ce9545 a prov:Activity ;
    dct:description "Freesurfer segmentation statistics" ;
    prov:qualifiedAssociation [ a prov:Agent ;
            prov:hadRole sio:Subject ;
            prov:wasAssociatedWith niiri:d2267bde-b25f-11e9-84fd-003ee1ce9545 ] .
  
niiri:d2267bde-b25f-11e9-84fd-003ee1ce9545 a prov:Agent,
        prov:Person ;
    ndar:src_subject_id "0026005"^^xsd:string .
```

**Comment by dbkeator** [comment]
@satra  Which file is that?  I don't see that in the ones I've looked at.  Maybe something left over from one of the iterations..

**Comment by satra** [comment]
example: datasets.datalad.org/adhd200/RawDataBIDS/Brown/nidm.ttl

**Comment by dbkeator** [comment]
@satra Actually that's because the original BIDS data has directory names as sub-0026005 but their participant.tsv file has the subject ID as 26005.  So, that's actually not a valid BIDS dataset I don't think.  

So this happens with ADHD200 sites Brown, NeuroIMAGE, NYU, Pittsburgh, and WashU.  

I guess I could go in and change all the IDs in the participant.tsv files to have the initial 00 but I won't be able to update the datalad accessible BIDS datasets....

**Comment by satra** [comment]
can you hack this in the conversion for now?

but also post an issue in the repo for (https://github.com/FCP-INDI/fcp_indi_bucket_maintenance) since the datalad pieces are simply pulled in from fcp-indi.

**Comment by dbkeator** [comment]
Regenerated the original BIDS-> NIDM-E conversions after adding the leading '00' to the offending IDs in the participants.tsv files.  Now re-generating all the Freesurfer and FSL additions.  Moved the old wBrainVols branch -> [wBrainVols_wrong_ADHD200_IDs](https://github.com/dbkeator/simple2_NIDM_examples/tree/wBrainVols_wrong_ADHD200_IDs).  New wBrainVols branch will be a new clean conversion and should address the issues here.  Also added issue to FCP-INDI
