### ISSUE TITLE
incorrect prefix in openneuro/ds000208

### ISSUE THREAD

**Issue by djarecka** [dbkeator/simple2_NIDM_examples#15]
Looks like [one of ttl file](https://github.com/dbkeator/simple2_NIDM_examples/blob/02356b84e71e8768eec6f352f853f035d0d92bae/datasets.datalad.org/openneuro/ds000208/nidm.ttl#L24) has an incorrect prefix `@prefix ns1: <http://iri.nidash.org/%>` that cause issues when uploading to oxigraph

**Comment by dbkeator** [comment]
This has been fixed in master and wBrainVols_7_2023 branches
