### ISSUE TITLE
Total brain volumes not in nidm.ttl files ?

### ISSUE THREAD

**Issue by jbpoline** [dbkeator/simple2_NIDM_examples#8]
@dbkeator  @satra  So, the problem as I see it:

- the file ../segstats_jsonld/segstats_jsonld/mapping_data/freesurfer-cdes.json contains 
 'http://purl.obolibrary.org/obo/UBERON_0013411': 'Estimated Total Intracranial Volume',

- The nidm files seems to also contain this : 
grep 0013411 */nidm.ttl 
Brown/nidm.ttl:    nidm:isAbout obo:UBERON_0013411 ;
KKI/nidm.ttl:    nidm:isAbout obo:UBERON_0013411 ;
NeuroIMAGE/nidm.ttl:    nidm:isAbout obo:UBERON_0013411 ;
NYU/nidm.ttl:    nidm:isAbout obo:UBERON_0013411 ;
[...]
but only in one record: 
fs:fs_000009 a fs:DataElement ;
    nidm:datumType <http://uri.interlex.org/base/ilx_0738276> ;
    nidm:isAbout obo:UBERON_0013411 ;
    nidm:measureOf <http://uri.interlex.org/base/ilx_0112559> ;
    fs:description "Estimated Total Intracranial Volume (mm^3)" ;
    fs:fsunit "mm^3" ;
    fs:hasUnit "mm^3" ;
    fs:key_source "Header" ;
    fs:label "Estimated Total Intracranial Volume (mm^3)" ;
    fs:measure "eTIV" ;
    fs:structure "EstimatedTotalIntraCranialVol" ;
    fs:unit "mm^3" .

- The awesome query (cf get_volumes_KeatorsAwesomeQuery.sparql in ../queries in the wBrainVols therefore do not find the values - hence they are not in the CSV. 

So, it seems that we dont have all the records in the ttl ... 
Or - quite possibly - I am missing something !

**Comment by satra** [comment]
@jbpoline - there are a few PRs that need to be merged on ants, freesurfer, and fsl. 

i think @dbkeator  is rerunning things, but i don't know where the things are.

**Comment by jbpoline** [comment]
@satra : ok - thanks for the quick response ... are you the one merging these ?
@dbkeator : is it just a matter of rerunning things to extract these values and create the new nidm.ttl once the merge is done ?

**Comment by satra** [comment]
@jbpoline - i don't have permissions to merge :) it's also good for someone else to take a look at the code before merging.

there are now two pieces to this:

1. the stats objects for each participant. 
2. the nidm data elements

the data elements are universal and should be generated only when the software changes. these graphs can be generated and created as a standalone file.

the stats objects are the ones that will have to be regenerated using the new models. i know keator was generating these, but i don't know the current status of which ones are done and which ones not.

**Comment by dbkeator** [comment]
@satra I just returned from a trip to NIH.  I am merging the changes to  [segstats_jsonld GitHub repo](https://github.com/dbkeator/segstats_jsonld) (Freesurfer one).  I will copy the changed fsl CDE / mapping files to the fsl tool repo [FSL](https://github.com/dbkeator/fsl_seg_to_nidm/.

Then I'll re-run the Freesurfer and FSL brain volumes add code and regenerate the simple 2 examples.  Then it can be checked by @jbpoline using the same query he has now and we'll see if that makes things better.  I have a few fires but will do this in the afternoon pacific time...

**Comment by dbkeator** [comment]
@satra I still don't see nidm:isAbout obo:UBERON_0013411 ; in any of the FSL data elements.  I think that's because FSL doesn't have an equivalent "Intracranial Volume" measure which is what I told @jbpoline at SFN.

**Comment by satra** [comment]
@dbkeator - indeed FSL doesn't have intracranial volume. in fsl this would be done presumably by adding up gray + white + csf

**Comment by jbpoline** [comment]
but, I believe I should find the FS UBERON_0013411 in the ttl with the data, I dont atm

**Comment by jbpoline** [comment]
@dbkeator  @satra  : but, I believe I should find the FS UBERON_0013411 in the ttl with the data, I dont atm

**Comment by jbpoline** [comment]
sorry - wrong close !

**Comment by dbkeator** [comment]
@satra I agree, that's what I told @jbpoline ...add up wm, gray, csf.

@jb I see it's because the query is returning only structures that have isAbout in both softwares.  Thought that was what you needed.  Will update the query

**Comment by dbkeator** [comment]
@jbpoline I updated the [query](https://github.com/dbkeator/simple2_NIDM_examples/blob/wBrainVols/queries/get_volumes_KeatorsAwesomeQuery.sparql)  It also had the hasLaterality required which ETIV does not.  now it should return structures whether they have an isAbout or laterality.   This AM I thought I had to re-run the FSL and Freesurfer stuff again so my latest push of the NIDM files to the repo is without brain volumes (so don't git pull it yet).  The FSL scripts are done but the Freesurfer ones are still running and I need to leave so I'll push those up in the AM.  You can use the query included in the link above if you want to run it tonight just replace the one you have in the repo...

**Comment by jbpoline** [comment]
@dbkeator   - yes - summing the gray + white + csf  should be fine for FSL, thanks for adding the FS 
Will work on this this PM 

One question on the query:
bind(IF(?Gender ="1"^^xsd:string, "Male"^^xsd:string,"Female"^^xsd:string) as ?Gender)
is sufficient ? is it  only testing if Gender == 1 ?

**Comment by dbkeator** [comment]
@jbpoline Ok, you should be good to do a git pull, get the latest NIDM files and the latest query and run it.  I have tested the keator awesome query and it appears to return the information you're requesting...

**Comment by dbkeator** [comment]
@jbpoline the bind Gender mapping step just does a value -> text conversion.  Can't remember if it was Abide or ADHD200 that stored gender as 1 == Male and 2 == Female.  The other dataset had stored Male and Female strings.  So, this binding step basically says if the gender is a 1 then we'll output it as "Male"..so that your output CSV file has the same string in that column across datasets....

**Comment by jbpoline** [comment]
@dbkeator  Right, I was just wondering why there wasnt a 'IF Gender = 2' bit ... my bad of not knowing sparql I suppose !

**Comment by dbkeator** [comment]
@jbpoline I think there's still something weird about the query.  Looking into it....

**Comment by jbpoline** [comment]
ok - thanks !

**Comment by jbpoline** [comment]
@dbkeator 
Hey : could you send me your result csv ? the updated query+nidm.ttl do not seem to give me any results ... will debug but meanwhile could get going with your csv
